import datetime
from ib_insync import *
import os
import time
import asyncio
from sqlalchemy import create_engine
import psycopg2 as pg
import io
import pandas as pd

engine = create_engine('postgresql://stocks:stocks@localhost:2345/option_price_tracking')
connection = engine.connect()
ib = IB()
ib.connect('127.0.0.1', 7496, clientId=12)

# "SPY","QQQ","EEM","IWM","XLF","GLD","EFA","VXX","USO","XOP","FXI","HYG","AAPL","BAC","MU","FB","BABA","NVDA","GE","AMD","TSLA","NFLX","AMZN","MSFT","SNAP","T","C","CHK","WMT","JPM","INTC","CSCO","TWTR","NXPI","DIS","XOM","BA","WFC","F",
# "AMAT","JD","ABBV","SQ","PBR","BIDU","GOOGL","M","CVX","GS","GM","X","CAT","HD","CELG","VZ","IBM","JCP","PYPL","GILD","WLL",
# "VRX","TEVA","FCX","CRM","MGM","SYMC","AAL","GOOG","PFE","ADBE","ROKU","RIG","SLB","QCOM","HMNY","MRK","CLF","V","KO","MA","CVS","DAL","JNJ","TGT","COST","UPS","CMCSA","LOW","SBUX","ORCL","WDC","DE","MS","BP","HAL","MCD","AKS","DVN","ETP","MRO","ATVI","BKNG","WYNN","CTL","BBY","LUV","EA","BMY","DB","WHR","PG","AVGO","CMG","NKE","KKR","GME","AMGN","APC","HTZ","BOX","DISH",
# "NBR","IQ","DWDP","KMI","CIT","LULU","UAA","KR","MDLZ","BB","SN","PEP","UNH","UTX","WFT","COP","MTCH","LB","ADSK","GPS","TWX","UAL","VLO","APA","FIT","LRCX","STX","AIG","HPQ","SWN","NTES","KHC","LMT","HLF","FTR","PM","WB","MYL","MO","FEYE","SPOT","OXY","AGN","ABX","DDD",
# "YELP","VALE","UNP","JNPR","AA","PANW","LVS","KSS","MDT","AXP","GPRO","MMM","OLED","EBAY","DLTR","AABA","EOG","BUD","FSLR","SPLK","P","MOMO","MPC","DKS","TTWO","LNG","CIEN","TXN","TRIP","YNDX","ILG","RTN","THC","CY","SWKS","SHOP","MT","HIG","TMUS","WBA","DHI","RRC","NE","AAOI","CZR","STI","WMB","CPB","TWLO","BZUN","FDX","MET","GERN","ABT","NYLD","OSTK","MDXG","VIPS","ZNGA","NEM","NWL","GIS","AFL","REGN","GLW","BWP","MRVL","NTNX","ESRX","NTAP",
# symbol_list = ["SPY", "QQQ", "EEM", "IWM", "XLF", "GLD", "EFA", "VXX", "USO", "XOP", "FXI", "HYG", "AAPL", "BAC", "MU",
#                "FB", "BABA", "NVDA", "GE", "AMD", "TSLA", "NFLX", "AMZN", "MSFT", "SNAP", "T", "C", "CHK", "WMT", "JPM",
#                "INTC", "CSCO", "TWTR", "NXPI", "DIS", "XOM", "BA", "WFC", "F", "AMAT", "JD", "ABBV", "SQ", "PBR",
#                "BIDU", "GOOGL", "M", "CVX", "GS", "GM", "X", "CAT", "HD", "CELG", "VZ", "IBM", "JCP", "PYPL", "GILD",
#                "WLL", "VRX", "TEVA", "FCX", "CRM", "MGM", "SYMC", "AAL", "GOOG", "PFE", "ADBE", "ROKU", "RIG", "SLB",
#                "QCOM", "HMNY", "MRK", "CLF", "V", "KO", "MA", "CVS", "DAL", "JNJ", "TGT", "COST", "UPS", "CMCSA", "LOW",
#                "SBUX", "ORCL", "WDC", "DE", "MS", "BP", "HAL", "MCD", "AKS", "DVN", "ETP", "MRO", "ATVI", "BKNG",
#                "WYNN", "CTL", "BBY", "LUV", "EA", "BMY", "DB", "WHR", "PG", "AVGO", "CMG", "NKE", "KKR", "GME", "AMGN",
#                "APC", "HTZ", "BOX", "DISH", "NBR", "IQ", "DWDP", "KMI", "CIT", "LULU", "UAA", "KR", "MDLZ", "BB", "SN",
#                "PEP", "UNH", "UTX", "WFT", "COP", "MTCH", "LB", "ADSK", "GPS", "UAL", "VLO", "APA", "FIT",
#                "LRCX", "STX", "AIG", "HPQ", "SWN", "NTES", "KHC", "LMT", "HLF", "FTR", "PM", "WB", "MYL", "MO", "FEYE",
#                "SPOT", "OXY", "AGN", "ABX", "DDD", "YELP", "VALE", "UNP", "JNPR", "AA", "PANW", "LVS", "KSS", "MDT",
#                "AXP", "GPRO", "MMM", "OLED", "EBAY", "DLTR", "AABA", "EOG", "BUD", "FSLR", "SPLK", "P", "MOMO", "MPC",
#                "DKS", "TTWO", "LNG", "CIEN", "TXN", "TRIP", "YNDX", "ILG", "RTN", "THC", "CY", "SWKS", "SHOP", "MT",
#                "HIG", "TMUS", "WBA", "DHI", "RRC", "NE", "AAOI", "CZR", "STI", "WMB", "CPB", "TWLO", "BZUN", "FDX",
#                "MET", "GERN", "ABT", "NYLD", "OSTK", "MDXG", "VIPS", "ZNGA", "NEM", "NWL", "GIS", "AFL", "REGN", "GLW",
#                "BWP", "MRVL", "NTNX", "ESRX", "NTAP", "ANF", "BBT", "STZ", "CSX", "SVU", "AZN", "NOC", "SDRL", "SHAK",
#                "CBS", "KORS", "MNST", "VMW", "HES", "SYF", "TROX", "IP", "BX", "DNR", "FL", "URBN", "ADM", "I", "AMTD",
#                "PAGS", "TAL", "TIF", "HON", "CTRP", "GG", "COTY", "ETE", "SRPT", "W", "EVHC", "DBX", "HPE", "GRPN",
#                "ALXN", "RHT", "ULTA", "AMBA", "YY", "BBBY", "LBTYA", "SO", "Z", "IGT", "CRC", "LLY", "FOSL", "USB",
#                "BIIB", "OPK", "CL", "URI", "NRG", "PTLA", "SCHW", "NOK", "PAY", "PXD", "TOL", "K", "ALGN", "ESV", "PSX",
#                "CWH", "ARNC", "ETFC", "CMI", "AZO", "MNK"]
# symbol_list = ["SPY", "QQQ", "EEM", "IWM", "XLF", "GLD", "EFA", "VXX", "USO", "XOP", "FXI", "HYG", "AAPL", "BAC", "MU",
#                "FB", "BABA", "NVDA", "GE", "AMD", "TSLA", "NFLX", "AMZN", "MSFT", "SNAP", "T", "C", "CHK", "WMT", "JPM",
#                "INTC", "CSCO", "TWTR", "NXPI", "DIS", "XOM", "BA", "WFC", "F", "AMAT", "JD", "ABBV", "SQ", "PBR",
#                "BIDU", "GOOGL", "M", "CVX", "GS", "GM", "X", "CAT", "HD", "CELG", "VZ", "IBM", "JCP", "PYPL", "GILD",
#                "WLL", "VRX", "TEVA", "FCX", "CRM", "MGM", "SYMC", "AAL", "GOOG", "PFE", "ADBE", "ROKU", "RIG", "SLB",
#                "QCOM", "HMNY", "MRK", "CLF", "V", "KO", "MA", "CVS", "DAL", "JNJ", "TGT", "COST", "UPS", "CMCSA", "LOW",
#                "SBUX", "ORCL", "WDC", "DE", "MS", "BP", "HAL", "MCD", "AKS", "DVN", "ETP", "MRO", "ATVI", "BKNG",
#                "WYNN", "CTL", "BBY", "LUV", "EA", "BMY", "DB", "WHR", "PG", "AVGO", "CMG", "NKE", "KKR", "GME", "AMGN",
#                "APC", "HTZ", "BOX", "DISH", "NBR", "IQ", "DWDP", "KMI", "CIT", "LULU", "UAA", "KR", "MDLZ",
#                "BB", "SN", "PEP", "UNH", "UTX", "WFT", "COP", "MTCH", "LB", "ADSK", "GPS", "UAL", "VLO", "APA",
#                "FIT", "LRCX", "STX", "AIG", "HPQ", "SWN", "NTES", "KHC", "LMT", "HLF", "FTR", "PM", "WB", "MYL", "MO",
#                "FEYE", "SPOT", "OXY", "AGN", "ABX", "DDD", "YELP", "VALE", "UNP", "JNPR", "AA", "PANW", "LVS",
#                "KSS", "MDT", "AXP", "GPRO", "MMM", "OLED", "EBAY", "DLTR", "AABA", "EOG", "BUD", "FSLR", "SPLK", "P",
#                "MOMO", "MPC", "DKS", "TTWO", "LNG", "CIEN", "TXN", "TRIP", "YNDX", "ILG", "RTN", "THC", "CY", "SWKS",
#                "SHOP", "MT", "HIG", "TMUS", "WBA", "DHI", "RRC", "NE", "AAOI", "CZR", "STI", "WMB", "CPB", "TWLO",
#                "BZUN", "FDX", "MET", "GERN", "ABT", "NYLD", "OSTK", "MDXG", "VIPS", "ZNGA", "NEM", "NWL", "GIS", "AFL",
#                "REGN", "GLW", "BWP", "MRVL", "NTNX", "ESRX", "NTAP", "ANF", "BBT", "STZ", "CSX", "SVU", "AZN",
#                "NOC", "SDRL", "SHAK", "CBS", "KORS", "MNST", "VMW", "HES", "SYF", "TROX", "IP", "BX", "DNR", "FL",
#                "URBN", "ADM", "I", "AMTD", "PAGS", "TAL", "TIF", "HON", "CTRP", "GG", "COTY", "ETE", "SRPT", "W",
#                "EVHC", "DBX", "HPE", "GRPN", "ALXN", "RHT", "ULTA", "AMBA", "YY", "BBBY", "LBTYA", "SO", "Z", "IGT",
#                "CRC", "LLY", "FOSL", "USB", "BIIB", "OPK", "CL", "URI", "NRG", "PTLA", "SCHW", "NOK", "PAY", "PXD",
#                "TOL", "K", "ALGN", "ESV", "PSX", "CWH", "ARNC", "ETFC", "CMI", "AZO", "MNK", "SNCR", "HOG", "DG",
#                "ESPR", "CHRW", "ALB", "ISRG", "ADP", "EXEL", "COF", "TSM", "NUE", "AKRX", "AUY", "HIMX", "SKX", "OAS",
#                "SIRI", "WPM", "PSTG", "SLCA", "HBI", "TTD", "FOLD", "CBOE", "ANET", "TSN", "CRSP", "NOW", "SGMO", "RL",
#                "JWN", "WTW", "CI", "UNIT", "XRX", "WDAY", "EL", "EXPE", "GLNG", "SHLD", "A", "AMT", "RIOT", "PRU",
#                "WATT", "DO", "HFC", "VKTX", "CF", "EPD", "QD", "AG", "HSBC", "ON", "TXMD", "SU", "VOD", "PCG", "CAR",
#                "MDR", "IMMU", "ARWR", "UA", "TJX", "INTU", "ECA", "MAT", "AKAM", "SPWR", "S", "TRN", "CTSH", "CCL",
#                "SGMS", "CLR", "MCK", "DUK", "WSM", "GSK", "ALK", "SIG", "ITUB", "SEAS", "CCJ", "FOXA", "NOG", "GNW",
#                "MOS", "KEY", "KEM", "FDC", "AOBC", "PVH", "SBGI", "GRUB", "HCLP", "ENPH", "SM", "CB", "OHI",
#                "CLX", "AVP", "LEN", "FITB", "PE", "AAXN", "BHP", "QEP", "DXC", "CMA", "LITE", "MAR", "SAN", "APRN",
#                "CS", "RCL", "AKAO", "CRUS", "NLY", "LGCY", "STMP", "SEDG", "CME", "GD", "BSX", "SINA", "TECK", "MELI",
#                "NKTR", "OCN", "COG", "BURL", "GT", "ACAD", "TAP", "RF", "CLBK", "RIO", "AAP", "TPX", "WP",
#                "CRZO", "IAC", "BHGE", "FCAU", "NSC", "BK", "GOGO", "SGYP", "QRVO", "AEO", "ICE", "ENDP", "GPOR", "ADI",
#                "GGB", "MLCO", "TRXC", "XLNX", "VIRT", "CRON", "FANG", "EXPR", "JACK", "SYY", "EDIT", "CXO", "EDU",
#                "EXAS", "PAH", "ROST", "NEPT", "RH", "EXC", "DF", "GOOS", "PVG", "AMC", "KGC", "EMR", "VIAV", "WTI",
#                "DATA", "YUM", "AET", "KNX", "PNC", "CROX", "HUN", "NTR", "JBLU", "MAS", "STNG", "ETN", "ICHR", "KMB",
#                "FNSR", "BYD", "CX", "ETSY", "CTXS", "SNA", "XPO", "PZZA", "DSW", "RCII", "FLR", "FTI", "HIIQ", "SHPG",
#                "PI", "RUN", "AVEO", "TTM", "OMER", "VMC", "ACN", "PPL", "SPG", "EW", "CREE", "WWE", "NOV",
#                "PHM", "TS", "DFS", "YPF", "KBH", "ARLP", "NRZ", "JCI", "ACIA", "GBT", "CA", "ZTO", "HL", "FIVE", "TPR",
#                "AXDX", "ASH", "ZION", "UEPS", "TGTX", "LPX", "AEM", "DISCA", "HAIN", "ASNA", "CVNA", "D", "HPT", "KMX",
#                "ATUS", "ROK", "VEEV", "LYB", "CAH", "GES", "INCY", "BLK", "CARS", "BLUE", "NCLH", "OKTA", "LOXO", "WY",
#                "UBNT", "ETM", "ATHN", "AGNC", "VTR", "CNQ", "ODFL", "SWK", "BHF", "O", "BIG", "PRGO", "ENB", "DQ",
#                "STM", "YUMC", "MCHP", "ARRY", "NVO", "DVAX", "ILMN", "MVIS", "THO", "FLEX", "KSU", "GMED", "PF", "DVA",
#                "CSIQ", "CLDR", "CHS", "KOS", "HUBS", "OCLR", "EGO", "CC", "ITW", "ANTM", "PLUG", "TER", "HOME", "DVMT",
#                "LFIN", "TOT", "FLS", "PLNT", "SYK", "GWW", "TRV", "SJM", "WM", "PRTA", "MNKD", "BOFI", "ADT", "SPGI",
#                "INFN", "CNC", "AFSI", "NEE", "PAAS", "USG", "FTNT", "NUAN", "TRUE", "WUBA", "TSCO", "ABC", "VIAB",
#                "CFG", "WPZ", "HCA", "EQIX", "TSEM", "DECK", "CVRR", "STLD", "RAD", "PH", "CHL", "FAST", "SFLY", "CYH",
#                "PPC", "CG", "GGAL", "MBI", "HSY", "BG", "ARNA", "ZIOP", "ZN", "GWPH", "BPL", "VFC", "PEGI", "WEN",
#                "XNET", "AKCA", "COHR", "FLO", "SAIL", "GLUU", "CENX", "MMP", "DOCU", "CBL", "LPI", "JNCE", "TDG",
#                "CERN", "HDSN", "PAA", "BLL", "GBX", "IRBT", "CLMT", "LNC", "KBR", "SFM", "EXP", "NFX", "RMTI", "PPG",
#                "BBD", "OKE", "PLCE", "SESN", "EIX", "GSS", "QCP", "VREX", "EMES", "SSYS", "HBAN", "WING", "IVAC",
#                "PSEC", "HLT", "CARA", "TRGP", "VRTX", "BGS", "IBKR", "PAYC", "GDEN", "LBTYK", "JELD", "EQT",
#                "GTN", "AMRN", "MZOR", "NBL", "FE", "TEX", "HUM", "DBD", "FLT", "TROW", "DK", "WELL", "RDN",
#                "NXST", "LKQ", "TV", "RES", "ESIO", "ZOES", "IMGN", "MUR", "NYCB", "AMRS", "WPX", "BCS", "XRAY", "ABMD",
#                "PAYX", "SFIX", "NVAX", "XON", "XEC", "LC", "LL", "INSY", "MSI", "SD", "IR", "TEAM", "ARCC", "LOGI",
#                "ANDV", "NLNK", "HRL", "CLVS", "FMI", "JMEI", "VSTM", "NAK", "HP", "WRD", "CVI", "KODK", "CLNE", "RMBS",
#                "PBYI", "CHTR", "DRI", "PAGP", "PGR", "MLM", "QSR", "RDFN", "EVBG", "NGD", "AU", "KLAC", "GNC", "BAX",
#                "SC", "TIVO", "SQM", "TSRO", "ZBRA", "CNX", "BMRN", "MIC", "GRMN", "TMO", "ZTS", "AGRX", "PX", "ALL",
#                "KIN", "KERX", "BITA", "EVRI", "TXT", "GDDY", "RACE", "DDS", "DPZ", "LCI", "ENT", "KTOS", "SHW", "PENN",
#                "TD", "AEP", "ALRM", "FFIV", "SODA", "ASUR", "PTEN", "HA", "CGNX", "USCR", "IVZ", "ECYT", "SORL", "SKT",
#                "AQMS", "FRO", "RNG", "APO", "RDNT", "NBIX", "AMAG", "CPE", "ED", "CAG", "ATHM", "MUX", "WGO", "CORT",
#                "CLB", "CPRT", "SAP", "FMC", "CDE", "PCAR", "AMWD", "HTHT", "RY", "ADMP", "CCI", "HRTX", "SNE", "TRVG",
#                "RRD", "CTAS", "TELL", "MTZ", "AGO", "CVE", "ADNT", "GALT", "SAVE", "YRD", "DNKN", "BPT", "SSW", "SYNA",
#                "ALLY", "BJRI", "KLIC", "ICPT", "IFF", "CEO", "GDS", "MPLX", "LX", "SNY", "TAHO", "IBN", "SAND", "NTRI",
#                "ABEO", "TZOO", "YRCW", "MTOR", "AXL", "AES", "CBB", "ODP", "BLMN", "LGIH", "HRB", "CONE", "NDAQ", "VHC",
#                "OLN", "MC", "SOHU", "SIVB", "HK", "IEP", "NCR", "HDB", "DY", "SMPL", "AVB", "SBRA", "HMY", "LYV",
#                "MFGP", "ANDX", "BZH", "EEP", "DOV", "BECN", "DHR", "NAV", "CPG", "RGLD", "ACRX", "CBRL", "PBI",
#                "HAS", "NVTA", "IONS", "FND", "GTT", "LLL", "HRG", "SRNE", "HZNP", "OMC", "OMEX", "DLR", "COUP", "JEC",
#                "ONVO", "CRK", "LSI", "DIN", "SWCH", "SFL", "JKS", "EXTR", "GPRE", "VRNT", "FTK", "CAKE",
#                "TRTN", "AMBC", "NAT", "RRGB", "WRK", "UBS", "SMG", "RJF", "NVS", "TDC", "AVAV", "NYT", "EMN", "SEE",
#                "HOLX", "SNH", "SPPI", "IPGP", "NAP", "APD", "IAG", "EPC", "ERF", "ELLI", "EGN", "HDS", "FRTA", "STT",
#                "BGFV", "OC", "SAFM", "CAVM", "UPL", "ZS", "VAC", "CLSD", "RGNX", "AMCX", "ERI", "HIBB", "AY", "WPG",
#                "BDC", "WTTR", "DXCM", "JAG", "PDCO", "CMCM", "SNP", "RENN", "SAGE", "HLTH", "EC", "ECL", "GRA", "KL",
#                "IPG", "VICR", "PIR", "AIZ", "AYI", "SCHN", "EFX", "ACXM", "ALNY", "TDOC", "SPH", "SA", "ERJ", "NG",
#                "XOG", "HRS", "PII", "GMLP", "BDX", "RDUS", "CATM", "DEO", "HCP", "BERY", "NS", "DERM", "AMX",
#                "ACM", "GOLD", "PGNX", "SSRM", "GPN", "MFIN", "BGCP", "INO", "EQR", "IPI", "ATRS", "CHKP", "BKD", "IRM",
#                "JAZZ", "IMAX", "UNM", "QNST", "PTR", "PETS", "PXLW", "MXIM", "TKR", "CIG", "VRSN", "CAF", "DM", "VNOM",
#                "CSOD", "CRTO", "ARW", "JILL", "MYGN", "LEA", "PVTL", "IDTI", "SEP", "HDP", "REN", "EQM", "CP", "ARCO",
#                "AR", "WMGI", "AUPH", "OI", "AGIO", "ALKS", "INFY", "STON", "AERI", "MCO", "SWIR", "ZG", "CRR",
#                "TK", "AN", "HCC", "AGEN", "XLRN", "GDOT", "BEAT", "UIS", "QUIK", "NEWR", "QURE", "MGA", "BEN", "UCTT",
#                "PLAY", "SID", "NGL", "SSI", "SPHS", "SSP", "PBF", "MTDR", "MDB", "AFMD", "NTLA", "AMID", "CTRL", "FGEN",
#                "IRDM", "UTHR", "BTG", "CPRX", "ADS", "TREE", "CHU", "DSX", "MHK", "XXII", "DEPO", "ZAGG", "ABEV",
#                "FLNT", "EDR", "PWR", "MLNT", "KLXI", "OTEX", "SND", "SMRT", "QIWI", "NPTN", "CYBR", "WIX", "HEI", "GGP",
#                "ANW", "HALO", "WPRT", "VNET", "NTRS", "ATRA", "AQXP", "LIVN", "HII", "CYOU", "PKG", "APTV", "VRAY",
#                "ZEN", "EGC", "MARK", "CMRE", "ATI", "BLDP", "EROS", "DGX", "CASY", "IDCC", "SOGO", "BLCM", "CQP", "KIM",
#                "MSG", "PFPT", "BOLD", "USAT", "BW", "EAT", "NDLS", "SHLX", "FRED", "SNPS", "MCRI", "SSTK",
#                "NBRV", "CAL", "EXPD", "STOR", "IDRA", "PFG", "AMP", "TIS", "ASML", "ZBH", "IQV", "SUPN", "FNV", "RGR",
#                "ONCE", "GPC", "MEET", "BOJA", "WU", "SGEN", "PCRX", "ING", "VVUS", "LH", "CSII", "DHT", "CRBP", "FLIR",
#                "MKC", "SBAC", "VCEL", "BNS", "LEE", "INAP", "ENVA", "BGNE", "EGHT", "BTU", "NHTC", "LE", "MED", "LKM",
#                "JBL", "MMLP", "REGI", "EPR", "SUN", "CCK", "BMA", "OSUR", "MDC", "AER", "RNR", "VRNS", "INGN", "FIS",
#                "PVAC", "AMPE", "BSM", "REV", "WLK", "FISV", "SBNY", "YEXT", "VRA", "SE", "BSTI", "AON", "BRS", "MDRX",
#                "LXFT", "QLYS", "IMMR", "KW", "EVC", "NMRK", "POST", "EVR", "CDEV", "BKS", "SIX", "WETF", "RDC", "MEOH",
#                "VST", "HSIC", "HQY", "THS", "HHC", "VSI", "ZAYO", "PSA", "MPW", "SCCO", "HLX", "GPK", "PRMW", "HOS",
#                "FRAC", "XYL", "CONN", "EPE", "BAM", "VOYA", "XCRA", "HST", "IIVI", "EVA", "RGEN", "ORLY", "SBGL",
#                "RESI", "SRG", "EGAN", "TEN", "SEND", "NLSN", "GEL", "AMR", "ABAX", "FN", "BR", "CDNS", "CHGG", "MTG",
#                "KPTI", "AXAS", "BOOT", "GOV", "EXK", "CERS", "ADMS", "BREW", "LOGM", "CNP", "ACOR", "SBLK", "ATHX",
#                "CPLP", "TCS", "ZGNX", "TWOU", "SRE", "IDXX", "MKSI", "CMC", "TM", "VERU", "FCEL", "BTE", "DCP", "SMLP",
#                "FSM", "ETR", "BBVA", "PNR", "ASPS", "EPAM", "KNDI", "CALM", "SNDR", "EXR", "PHG", "BTI", "ENLK", "FIZZ",
#                "BKE", "REVG", "PEGA", "MAC", "TLRD", "AMOT", "PTX", "BPOP", "ACGL", "ROYT", "MIDD", "BFR", "SDLP",
#                "VVV", "CDW", "ATSG", "PRTK", "USFD", "TRI", "WIN", "MACK", "NCMI", "MTW", "TEF", "RLGY", "DLPH", "LYG",
#                "GWRE", "CRMT", "LILAK", "CEQP", "MRTX", "CARB", "PEG", "CNET", "MTSI", "ZYNE", "MBT", "INFI", "UNFI",
#                "FSCT", "CNI", "RVLT", "ADAP", "VECO", "AXTI", "EZPW", "PDS", "FHB", "PDLI", "BXP", "DAN", "TLYS", "AMN",
#                "LOMA", "QRTEA", "TX", "SCG", "ANFI", "BCOR", "TOO", "UVV", "SRT", "PCTY", "SNR", "TCO", "NVCR", "JBHT",
#                "ARCB", "VUZI", "ELF", "IDT", "MTB", "LGND", "EGOV", "ARQL", "CXW", "AXON", "EGRX", "IT", "DSKE",
#                "SPN", "INSM", "ARLZ", "BMS", "SATS", "SGRY", "MMC", "ELY", "LM", "TGP", "SRCL", "ERIC", "EVTC", "BCO",
#                "TCP", "AL", "VNO", "AJRD", "R", "LPLA", "HPR", "COHU", "CE", "NYMX", "FOX", "MXWL", "EBIX", "TECD",
#                "RPXC", "BAH", "XRF", "TGB", "UGP", "AXTA", "ENBL", "GSM", "RIGL", "OLLI", "INFO", "CIM", "CPA", "GLOG",
#                "RESN", "NICE", "ENR", "MAG", "DISCK", "TPH", "KRO", "MIK", "ABB", "RYAM", "BAS", "UN", "LPSN", "MSCI",
#                "FANH", "DPS", "SREV", "TITN", "WCG", "TRMB", "SBH", "IRTC", "IMPV", "BCC", "GEO", "AMG", "HOV", "HOLI",
#                "VGR", "OPY", "TSS", "STAA", "ALSN", "AWK", "PTCT", "AYR", "AEG", "TGI", "MYE", "DPLO", "BWA", "KELYA",
#                "CCLP", "ERII", "NOAH", "SLG", "PLD", "CHD", "WAB", "LADR", "TREX", "ARDX", "KALA", "QTWO", "CRCM",
#                "ATTU", "HBM", "RRR", "VOC", "CFR", "GLYC", "LOPE", "LOCO", "RP", "PEI", "CTSO", "CLNS", "HEES", "GROW",
#                "APH", "ASYS", "AEIS", "ULTI", "PBCT", "PSTI", "NSH", "DAR", "CLD", "UIHC", "SMTC", "WWW", "SKM", "LAMR",
#                "JCOM", "CRAY", "BEL", "EYES", "ARE", "WTS", "APT", "ECR", "RMD", "CPS", "ITCI", "TEL", "DNOW", "ARRS",
#                "AM", "AB", "BID", "MRCY", "NSP", "SPA", "HESM", "PEIX", "MD", "SAM", "ASMB", "NDSN", "CALX", "JOE",
#                "COO", "REI", "SRC", "FLXN", "BCRX", "NSU", "AZUL", "INGR", "MDCO", "JOBS", "LLNW", "CMS", "RBS", "CACC",
#                "CALL", "LDOS", "CMP", "NVRO", "BPMC", "APTI", "CAPL", "RS", "MDP", "PAM", "MARA", "QTNA", "LBY", "NUS",
#                "KMT", "CRI", "PCOM", "TPIC", "AGI", "BRFS", "FBP", "XOXO", "BLD", "VIVE", "OSK", "RSG", "AGCO", "TRQ",
#                "BRKS", "LAZ", "SMCI", "BDSI", "AAV", "AREX", "ALGT", "CNSL", "SPAR", "GST", "AROC", "CM", "MNRO",
#                "VSLR", "OZM", "BMO", "COMM", "EYPT", "AMSC", "TIER", "HSC", "MFC", "TEO", "DOX", "TDW", "TYL", "GTLS",
#                "CECO", "LFC", "BANC", "ORC", "FIVN", "ARMK", "CSTE", "NMM", "MAN", "RARE", "LW", "BNFT", "EIGI", "MSTR",
#                "APU", "VCYT", "CNK", "RYB", "CTB", "TWO", "SRCI", "TTPH", "SLM", "PAG", "CYTK", "COL", "SCVL",
#                "BLDR", "DS", "GEOS", "WSBF", "OZRK", "COLL", "CVG", "VIVO", "ARAY", "ST", "UFS", "ECHO",
#                "MB", "RBA", "UEC", "MEIP", "ECOM", "TOCA", "PETQ", "BOOM", "DOC", "OCUL", "SXCP", "QSII", "H", "AXGN",
#                "CMPR", "CAI", "CLDX", "AUO", "CUBE", "WCN", "HRI", "UPLD", "INVA", "CLLS", "FDS", "ZUMZ", "GKOS", "RPD",
#                "AVXL", "ROP", "NGG", "BC", "BLKB", "CDXC", "PDCE", "PBFX", "ALDR", "ZNH", "TEGP", "PER", "ARII", "OBE",
#                "LEG", "VG", "XONE", "OXSQ", "AMKR", "ABR", "SDT", "CVA", "WAT", "PRLB", "ENS", "GSUM", "MTN",
#                "ASGN", "CJ", "BCLI", "MOV", "ZUO", "MGI", "SEMG", "GLP", "PERY", "SIMO", "GFI", "PODD", "AAWW", "TRNC",
#                "PTC", "STAR", "NUVA", "FMX", "MASI", "NANO", "MLNX", "BWXT", "WEC", "CBRE", "MDSO", "EPAY", "CTRN",
#                "INVH", "CRS", "SNSS", "DFIN", "IRT", "DDR", "FRAN", "TXRH", "WAIR", "ANGI", "SCI", "FET", "MX", "RAVN",
#                "LKSD", "OFG", "TCBI", "CZZ", "HABT", "ACLS", "GTS", "TUP", "INXN", "MERC", "WIFI", "MODN", "OMF", "WEB",
#                "TGNA", "LHO", "FRT", "CARG", "PPDF", "LPL", "RPM", "PETX", "LPCN", "CBU", "PACB", "GOGL",
#                "PRAA", "ZLAB", "MOH", "FCFS", "RFP", "AINV", "CUTR", "IART", "GORO", "MAIN", "OAK", "CDK", "FRPT",
#                "CHDN", "VNTR", "COT", "FENG", "PGTI", "SPR", "TALO", "WPC", "FPI", "KOPN", "CVGW", "UMPQ", "SNDX",
#                "ARCH", "CBAY", "TPC", "JBGS", "HIVE", "GNRC", "QDEL", "CEIX", "FUN", "GCAP", "PSXP", "VSTO", "MXL",
#                "MITK", "EMMS", "SMSI", "LCII", "PRO", "PEB", "WSR", "SEIC", "AAN", "FNGN", "TWNK", "MCEP", "CDMO",
#                "LAD", "WK", "SRI", "CHT", "SYKE", "PES", "KEX", "PDFS", "LMRK", "WBAI", "WRLD", "FLY", "PCYG", "CXP",
#                "ENTG", "XBIT", "STWD", "KN", "RAIL", "ARTX", "NVEE", "BRX", "TRP", "XENT", "MMYT", "GLOP", "ESS", "MCF",
#                "AT", "GCI", "SSC", "DEA", "MANT", "CALA", "SJT", "XL", "TCPC", "RRTS", "TTEC", "OR", "SIR", "IRWD",
#                "BTX", "L", "TA", "TTEK", "VJET", "JE", "CMRX", "UMBF", "E", "SNV", "FICO", "FSIC", "LXRX", "EFII",
#                "GPI", "RDI", "BBOX", "CHUY", "BIP", "ONDK", "AVY", "ACC", "SVVC", "CSLT", "LFUS", "LZB", "VSAR", "AMED",
#                "PBPB", "BMCH", "UL", "FTAI", "WBS", "KMG", "NGVC", "OOMA", "NAVI", "NEOS", "NXTD", "ACET", "ENTA",
#                "RUBI", "TTMI", "VRS", "MHLD", "CADE", "NEO", "MBUU", "KNOP", "DNB", "KRG", "NVMI", "GLRE", "RTEC",
#                "SONC", "CYRX", "BCE", "CCE", "RXN", "DFRG", "ATH", "KIRK", "CNDT", "MNTA", "OII", "VMI", "SRLP", "VPG",
#                "GLDD", "SPB", "AHL", "CNO", "INT", "ACHN", "WTR", "XPER", "MRCC", "PKX", "WLKP", "DAKT", "HRC", "SAIC",
#                "AVT", "CQH", "LSTR", "NXRT", "KRA", "ITRI", "KANG", "TRU", "CCS", "OSIS", "ALEX", "EHTH", "HOMB",
#                "FNF", "LJPC", "FGP", "SLAB", "PACW", "FOE", "EGBN", "UUUU", "BAK", "GIII", "CMTL", "UVE", "USAC", "ATR",
#                "VRSK", "TCX", "CRNT", "ARR", "MAA", "GPT", "VEDL", "DPW", "CSV", "NRP", "RE", "NH", "MKL", "XIN", "ALV",
#                "FBHS", "NWSA", "AEE", "GAIN", "NSIT", "VER", "PRA", "AI", "SF", "PICO", "TWI", "VNDA", "TTS", "CVLT",
#                "AKG", "NAO", "ILPT", "ISCA", "AMRX", "NTGR", "FSTR", "ADXS", "CNXM", "PRAH", "VICI", "GCO", "AVHI",
#                "IVR", "MUSA", "PK", "BPI", "VSH", "ANSS", "HTA", "VOXX", "VTL", "SOI", "CO", "ESNT", "AGTC", "PRTY",
#                "CAMT", "QUAD", "VRTV", "FRGI", "BCEI", "RYN", "CMCO", "MSM", "VIV", "ESRT", "IPHI", "HGV", "NOVT",
#                "DENN", "JEF", "CRIS", "AKBA", "SKYW", "ROIC", "ORBK", "OTIC", "NFG", "GVA", "WLH", "CEVA", "MTRN",
#                "PLT", "SABR", "CINF", "CNAT", "LXU", "HY", "WAGE", "VC", "ITT", "DLX", "MCRN", "RST", "BCOV", "RLJ",
#                "WNC", "CLDT", "CCO", "PJT", "MGPI", "NX", "HNP", "CLI", "ZEUS", "PBA", "HEP", "AVDL", "AME", "VAR",
#                "CWT", "DXPE", "CTIC", "CAMP", "BSBR", "SBS", "WDR", "BL", "GATX", "MPWR", "AXE", "SWM", "APEI", "SPSC",
#                "GWR", "FHN", "CSTM", "WD", "AJG", "UHS", "MSB", "CFX", "NEP", "FCN", "WBC", "PARR", "SHOO", "XEL",
#                "OGS", "TKC", "TRCO", "SUM", "GHDX", "EAF", "EPZM", "JLL", "LTRPA", "DLNG", "KRNY", "SYNT", "VLP",
#                "INVE", "CW", "MKTX", "ANIP", "NEWT", "FOMX", "BVN", "DORM", "FUL", "WLTW", "CORR", "RDWR", "CNCE",
#                "RHI", "AIN", "EDGE", "FTSI", "AZZ", "INST", "FF", "SYNC", "SECO", "USNA", "STAG", "TTC", "STKL", "HASI",
#                "FPRX", "UNT", "GLPI", "ACTG", "HZO", "OUT", "CLS", "SRDX", "SVRA", "SNBR", "BABY", "FRSH", "UAN",
#                "BSMX", "BBL", "LN", "NSTG", "ACHC", "XNCR", "SAH", "SUI", "AXS", "CAJ", "MTH", "WES", "RICK", "SANM",
#                "VICL", "CRL", "GNTX", "RVNC", "ETH", "PSO", "SCS", "BHE", "CPSI", "ARA", "CPSS", "VSAT", "MDCA", "XHR",
#                "KYN", "RSPP", "SPWH", "SCWX", "PNFP", "ANIK", "ARES", "CTG", "LAND", "GPL", "KONA", "NTCT",
#                "OCSL", "MYOK", "QTM", "TEP", "BHVN", "WPP", "OPHT", "ZIXI", "LNTH", "WOR", "APOG", "MCC", "ARCT",
#                "MSGN", "TERP", "NERV", "GSAT", "AIRG", "SNX", "CODI", "QTS", "ATU", "VCRA", "HLIT", "TDS", "RTRX",
#                "TSE", "AAC", "PINC", "MYRG", "IOVA", "BBW", "SLRC", "MOBL", "BRG", "PATK", "KRNT", "GEF", "ADSW",
#                "HELE", "WERN", "SIGA", "AHT", "HMC", "VET", "MTX", "NVGS", "MRC", "ORAN", "ALLE", "FARO", "WGP", "NNN",
#                "USM", "MANH", "DKL", "NYMT", "EFC", "DCI", "LNN", "LXP", "IBP", "REDU", "LSXMA", "AIV", "BGG",
#                "ELGX", "FTV", "OCIP", "HXL", "PRI", "KAMN", "NM", "NDRO", "RYAAY", "BAP", "GHL", "HCI", "LII", "NHC",
#                "SON", "SMTX", "ES", "IBKC", "PSMT", "ACIW", "TMK", "EWBC", "ICON", "ENZ", "MANU", "TMHC", "UDR", "DRE",
#                "STE", "MTRX", "AAT", "DIOD", "CTRE", "VLY", "TVPT", "DSL", "MFA", "ISBC", "IEX", "EVLV", "ORIT", "NEWM",
#                "PMT", "BMI", "CMD", "SB", "MORN", "CYD", "TG", "PLX", "GOLF", "CYTR", "RWT", "WRI", "MBFI", "GIL",
#                "ECPG", "EQNR", "APPS", "LNDC", "WCC", "FBR", "LAUR", "BKU", "FBC", "FDP", "ATGE", "UNVR", "CASA",
#                "JASO", "ASIX", "AMRC", "SITE", "QUOT", "CPLA", "SCSC", "CGIP", "LQDT", "SHEN", "ASA", "TFSL",
#                "FELP", "THRM", "NI", "KAI", "AVID", "CRMD", "PLOW", "INOV", "DXLG", "LHCG", "UBSH", "OMED", "SUNW",
#                "FINL", "GLIBA", "ASB", "APDN", "ADUS", "PRGS", "ADTN", "STRA", "JNP", "ROG", "WIRE", "LEJU", "OVAS",
#                "PRFT", "MWA", "SLF", "POOL", "ICLK", "HTLD", "RCI", "SFE", "AAU", "HMSY", "EGLT", "SPXC", "HMHC",
#                "VYGR", "VBLT", "NR", "INSG", "DLB", "GSL", "RUSHA", "NTWK", "KOP", "G", "GNMX", "WIT", "CRESY", "RBC",
#                "RUTH", "EE", "B", "FCB", "WMC", "STRL", "GIFI", "DRH", "TRIB", "JMBA", "SFUN", "EQH", "STAY", "ROLL",
#                "CIO", "FLOW", "UFI", "EYE", "CACI", "HAE", "BIO", "RLI", "LSCC", "ADC", "GOOD", "LPNT",
#                "BOKF", "FAF", "ORBC", "SDR", "SALT", "SPNE", "CBSH", "HIFR", "TVTY", "BBSI", "BCPC", "AUTO", "GLT",
#                "DWSN", "TRNO", "AGFS", "ORI", "CTLT", "SLS", "QADA", "NNBR", "GPMT", "TCF", "MUFG", "UTSI", "CLIR",
#                "HIL", "NTP", "LBRDK", "ACRE", "IMO", "CECE", "RYI", "ABG", "CCXI", "TLGT", "CLGX", "AMH", "COLM",
#                "WTFC", "QGEN", "KEYW", "XRM", "MTL", "FBIO", "ABUS", "RSYS", "CENTA", "ACCO", "EV", "KT",
#                "ITGR", "HTH", "SENS", "FI", "CASH", "CPT", "PLXS", "OIS", "RCKT", "SSL", "INWK", "ANDE", "MITT", "PNM",
#                "ORN", "CWCO", "UGI", "NLS", "FWONK", "PKI", "TRVN", "AWR", "POL", "TOWR", "MMSI", "GRFS", "OGE", "ITG",
#                "CVBF", "OSG", "TNP", "ATO", "KNL", "ARDM", "SJR", "CRH", "AMBR", "CPLG", "MGEE", "SERV", "ALIM",
#                "LECO", "INTL", "MFCB", "PQG", "FORM", "EBS", "ASR", "MITL", "DBVT", "DRQ", "HURN", "CDAY", "MLHR",
#                "EMKR", "NWY", "PFGC", "ENLC", "NGS", "DTE", "MNTX", "OXM", "NSA", "TACO", "AIR", "SXC", "NCS",
#                "ATEN", "EGL", "NK", "CVEO", "CUB", "BIOS", "BKEP", "BSQR", "AWRE", "HCKT", "FIX",
#                "FTD", "HWCC", "EPM", "XCOOQ", "KAR", "MDU", "PBT", "SNN", "PJC", "REED", "TSQ", "RDY", "MATX", "TLP",
#                "APAM", "RBBN", "FMS", "CHH", "LYTS", "FBNC", "ARI", "CCMP", "ORA", "AGM", "RPT", "AZPN", "MPAA", "PNNT",
#                "COWN", "BXS", "WAL", "DHX", "AVA", "PHX", "CRAI", "DNLI", "HR", "LRN", "NEU", "POWI", "TRIL", "VEON",
#                "CYS", "GIB", "MCRB", "KALU", "TCAP", "TYPE", "AUDC", "EXLS", "MPX", "NNI", "TNK", "PDM", "CSGS", "AWI",
#                "GFF", "TUES", "WWD", "SXE", "BXE", "CSU", "ERA", "HYH", "TU", "BXMT", "SSD", "CIR", "EQC", "SIFY",
#                "ELP", "CNHI", "XAN", "CDZI", "GTE", "SHOS", "KOF", "HIW", "WABC", "WMS", "TPRE", "RMP", "LTXB", "CAAS",
#                "FSS", "ASTE", "HI", "MGP", "FMBI", "ROCK", "CMO", "POR", "RMAX", "SYRS", "ALT", "ACH", "MATW", "BHR",
#                "BSET", "BORN", "AVX", "CBPX", "DNN", "MN", "BRKR", "REG", "WSO", "BKCC", "AGRO", "LFGR", "TROV", "NPO",
#                "NCI", "IIIN", "CHE", "MTGE", "HUBG", "FLDM", "FORR", "BSAC", "EDAP", "LITB", "BRO", "CWST",
#                "MRTN", "NSM", "GEN", "REXR", "GZT", "RPAI", "JAKK", "TSU", "UFPI", "TOUR", "LOB", "NMIH", "NNVC",
#                "OCFC", "SBSI", "MGLN", "MVO", "PUK", "BDN", "CUR", "PCSB", "PRSC", "GV", "NVLN", "FDUS", "AXU", "GBCI",
#                "OFIX", "RHP", "SIGI", "MEI", "ORMP", "SNMX", "FCSC", "CAFD", "SEM", "DWCH", "JRJC", "SOL", "GEVO",
#                "EQGP", "IFN", "NMR", "OREXQ", "CCIH", "HSII", "SMFG", "TAT", "ECOL", "AHC", "RGS", "CNTY", "CPIX",
#                "EFOI", "HT", "PEO", "PFMT", "UTI", "ZFGN", "CBD", "SP", "ALLT", "CDTX", "KTCC", "PRKR", "RGLS", "SPNS",
#                "FLWS", "TBI", "OMN", "EHC", "SXT", "EEX", "NCTY", "NWPX", "SQBG", "ATNI", "AVH", "CGA", "CULP", "HRTG",
#                "HSTM", "INN", "PERI", "SAFE", "SPRT", "VLRS", "XSPA", "CKH", "ISIG", "CLH", "CNMD", "TAST", "AP",
#                "FWONA", "NFBK", "LBRDA", "IPCI", "KCAP", "DRD", "KNSL", "CHFC", "LPT", "BFAM", "BRC", "FLKS", "TILE",
#                "TMQ", "WRE", "EMAN", "KFY", "RGA", "SEAC", "CLFD", "BBU", "CIA", "DCO", "JONE", "KND", "SCHL",
#                "STCN", "UMC", "KBAL", "NWE", "LION", "SFBS", "BNCL", "CCRN", "DEI", "HBIO", "RNWK", "SEED", "SLGN",
#                "AVD", "CPF", "AEGN", "ARC", "CTS", "FCBC", "IMH", "TRC", "PSB", "ENIA", "GRC", "IRET", "SKIS",
#                "ANTH", "ASC", "DTEA", "ICAD", "MHO", "WLBA", "SR", "WAFD", "AHH", "GTY", "AMCN", "CGIX", "CYTX",
#                "HYGS", "MGIC", "PRK", "RM", "TRS", "CHKE", "FCF", "GLAD", "LRAD", "NEON", "OFC", "TRX", "VR",
#                "CHKR", "CUI", "ESE", "KS", "MATR", "NLST", "PFSW", "SHLM"]
# "BRK B", "XLC", "XLY", "XLP", "XLE", "XLV", "XLI", "XLRE", "XLB", "XLK", "XLU", "GDX", "UVXY", "EWZ",
# "TQQQ", "SQQQ", "AMLP", "IAU", "VWO", "JNK", "SVXY", "JNUG", "RSX", "IEMG",
# "EWJ", "DWT", "TVIX", "SPXL", "XBI", "DIA", "SPXS", "XRT", "DGAZ", "UGAZ", "EWW", "INDA", "AGG", "VGK", "EWY","EWC","UWT","IBB", "SOXS",
symbol_list = []


# "BRKB","MON","RDSA","TWX",
# symbol_list = ["NQ"]
# "SPX","RUT","MSCI","FTSE","NDX"
# SPX - RUT - MSCI - FTSE NDX
# "ES", "NQ-20", "GE", "OZ","LO", "OG"
# symbol_list = ["AZO","MNK"]
# sema = asyncio.Semaphore(10)
def get_contracts(cur_symbol):
    general_contract = Stock(symbol=cur_symbol, exchange="SMART", currency="USD")

    print("getting {}".format(cur_symbol))
    try:
        res = ib.reqContractDetails(general_contract)
    except ValueError:
        return None
    return [c.contract for c in res]


def main():
    for symbol in symbol_list:
        res = get_contracts(symbol)

        if res != None:
            result_df = util.df(res)
            result_df.to_sql("equity_contracts", engine, if_exists="append")


if __name__ == '__main__':
    start_time = time.time()
    main()
    print("Execution time was: {}".format(str(time.time() - start_time)))
